### ISSUE TITLE
[Request] in the Playlist Activity where there is options to (sort) the current Playlist make an (add) button next to it 

### ISSUE THREAD

**Issue by Dirkstaal** [marverenic/Jockey#106]
If the add button is clicked it launches a new Activity with all the songs in a list with an checkbox on the right side.

And on the toolbar is an done button so if 15 songs is checked it adds them to the current playlist

**Comment by Dirkstaal** [comment]
![Uploading Screenshot_2016-07-30-10-05-23.png…]()

**Comment by Dirkstaal** [comment]
Code that may help

public class PlaylistAddSongsActivity extends AppCompatActivity {
    SongsRecyclerAdapter adapter;
    Playlist playlist;
    RecyclerView recyclerView;
 
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (App.checkIfDataReady(this, getIntent())) {
            setContentView(R.layout.activity_playlistedit);
            this.playlist = App.getPlaylist(getIntent().getLongExtra(PlaylistActivity.KEY_PLAYLIST_ID, -1));
            Toolbar toolbar = (Toolbar) findViewById(R.id.main_toolbar);
            toolbar.setTitle("Add Songs");
            toolbar.setBackgroundColor(getResources().getColor(R.color.highlight_pressed));
            setSupportActionBar(toolbar);
            getSupportActionBar().setHomeButtonEnabled(true);
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
            this.recyclerView = (RecyclerView) findViewById(R.id.activity_playlistedit_recyclerview);
            this.recyclerView.setLayoutManager(new LinearLayoutManager(this));
            ArrayList<Song> songs = (ArrayList) App.getSongs().clone();
            Iterator it = this.playlist.songs.iterator();
            while (it.hasNext()) {
                songs.remove((Song) it.next());
            }
            this.adapter = new SongsRecyclerAdapter(songs, R.layout.listitem_song, new long[]{3});
            this.recyclerView.setAdapter(this.adapter);
            this.recyclerView.addItemDecoration(new DividerItemDecoration(this, 1));
        }
    }
 
    public void onBackPressed() {
        if (this.adapter.getSelection().size() == 0) {
            finish();
            return;
        }
        Builder builder = new Builder(this);
        builder.setMessage("Do you really want to leave? All changes will be discarded.");
        builder.setPositiveButton("Leave", new OnClickListener() {
            public void onClick(DialogInterface dialog, int which) {
                PlaylistAddSongsActivity.this.finish();
            }
        });
        builder.setNegativeButton("Stay", null);
        builder.show();
    }
 
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.playlistaddsongs, menu);
        return super.onCreateOptionsMenu(menu);
    }
 
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId())
            case R.id.action_playlistaddsongs_done:
                ArrayList songsToAdd = new ArrayList();
                for (Integer intValue : this.adapter.getSelection()) {
                    songsToAdd.add(this.adapter.getData().get(intValue.intValue()));
                }
                App.addToPlaylist((Context) this, this.playlist, songsToAdd, true);
                finish();
                break;
        }
        return true;
    }
}

**Comment by marverenic** [comment]
I'm kind of opposed to this since there's already a request (#39) to add the ability to select multiple songs on the library page and perform actions on all of them (including adding all of them to a playlist).

This implementation just seems like it would cause a duplication of features, and most music players don't seem to take this approach either.
