### ISSUE TITLE
Notification reappears even after closing it .

### ISSUE THREAD

**Issue by iampawan** [marverenic/Jockey#107]

**Comment by Dirkstaal** [comment]
You must actually  close the app first then slide the notification

**Comment by iampawan** [comment]
@Dirkstaal As i said it happens even after closing whenever audio get focus or when focus changes.

**Comment by marverenic** [comment]
#199 changes how the service is stopped, so this issue is probably invalid. Feel free to open a new issue if this still happens, though.
