### ISSUE TITLE
hi i am trying to implement highlight song name

### ISSUE THREAD

**Issue by Dirkstaal** [marverenic/Jockey#138]
Hi so I'm halfway there : 
If i select a song in the RecyclerView it gets selected but now i want to know what method gets the position of the current song  (if i skip or go previous) ?

**Comment by marverenic** [comment]
I'm not sure exactly what you're looking for, but I think you should take a look at the `PlayerController` class in the `player` package. It has a bunch of static methods to interact with the player service including `getNowPlaying()`, `getQueue()`, and `getQueuePosition()` which sounds like what you're looking for.

**Comment by Dirkstaal** [comment]
if (mBytes != null) {
      // Render all audio renderers
      AudioData audioData = new AudioData(mBytes);
      mRenderer.render(mCanvas, audioData, mRect);
    }

    if (mFFTBytes != null) {
      // Render all FFT renderers
      FFTData fftData = new FFTData(mFFTBytes);
      mRenderer.render(mCanvas, fftData, mRect);
    }

Ok i need to call this in the run method ?

* Ive got a new problem now my SurfaceView is not crashing but its not
rendering

*Only the background of the surfacview a grayish-black

* do you use ( setDataCaptureListener )
