### ISSUE TITLE
Crash: Now Playing

### ISSUE THREAD

**Issue by balzathor** [marverenic/Jockey#18]
Crashes when you click on "Now playing screen" below when nothing is playing.

**Comment by marverenic** [comment]
It should be fixed now as well as an artist page crash.

The code that caused the crash should have only happened on tablets in horizontal orientation on API < 21, but Crashlytics said that it happened on a Galaxy S5... Is your phone having an identity crisis? Does it think it's a tablet?

**Comment by balzathor** [comment]
I tested it on bluestacks, it gets detected as S5, idk how. Also when I test the debug version of my application on my Lenovo Tab it shows as Asus phone. Fabric really needs to get it together

**Comment by balzathor** [comment]
Can you add a build for the latest version? I can test it for you on a few phones and maybe report about it.

**Comment by marverenic** [comment]
A new version is available now. Jockey should prompt for an update with a Snackbar at the bottom of the library page.
