### ISSUE TITLE
Small Enhancement ideas for a big difference

### ISSUE THREAD

**Issue by nr9992** [marverenic/Jockey#23]
The latest commit is great with the addition of auto generated playlist and the ability to remove individual songs from the queue. There are a few quirks that I would suggest you to look into.

1. Display auto playlists on the top with a header distinction or something similar.
2. Recently played playlist.
3. Caching of data retrieved from last.fm, both images and biography in the background on app first run, with an option to update them individually. Would result in a lot of data saving and provide a much better UI experience.
4. Album art fetch for albums missing them. Makes the UI more uniform. Also, save them in cache for later use, if not embed them in the song's id3 tag.
5. id3 tag editor. I did try implementing it with My_id3 for android and it works for basic editing but using jaudiotagger would be great. I'm still looking into implementing that.
6. equalizer support. I know the description says that it won't have it but its a good thing to consider. I did set it up using the Audio Effects control panel and although it works, it sometimes is a miss on a few devices where the OEM has them removed or replaced with their own version, like HTC one and Motorola phones I tested one. I did some research and found out that there is a audiofxjava sample by google that can do the trick, but I am yet to find time to try implementing it. maybe you can.

There are also some UI improvements that can be made but if you can have these things implemented in a commit soon, I will make a pull request to clean up the UI. Let's do this

**Comment by marverenic** [comment]
Thanks for the input. A lot of these things are already on my radar, but here are my individual comments:

1. Some time around when AutoPlaylists can be made from the UI, I'll add the distinction between normal and auto playlists. I've also been debating over whether to show them at the top or not, so it's good to get an opinion on that.
2. This is certainly doable, but I hadn't thought about it before. This will probably make it into the AutoPlaylist update.
3. I think that the Last.fm library I use has caching built in, but I don't know if it actually works. This might be a bit more complicated than it sounds if I have to implement the cache myself, but still doable. This will probably be 2 feature releases after the AutoPlaylist update.
4. Kind of the same as number 3. Again, it probably won't happen for 2 more development cycles.
5. This is the next feature I'm looking into after AutoPlaylists. I haven't looked into what API's and libraries there are that do this, but thanks for the references.
6. TIL it's not actually that difficult to implement this (from what it seems like anyway). Apparently there's an Equalizer class provided by the Android SDK that you can associate with a MediaSession. I'll look into this some more, but I don't know where it fits in with the development cycles yet.

I don't have a firm ETA for any of these things with school and whatnot, but I'd guess that AutoPlaylists will be finished in September, tag editing in November, and Last.fm stuff in December.

**Comment by nr9992** [comment]
That's great. I'll also suggest using Glide instead of Picasso in the artist activity page for the artist image as Gllide has a better caching mechanism which considerably reduces image loading times for me now. For the time the app is in memory, Glide keeps a cache of previously fetched images. The network call is still made but image loading is way faster.

Use this snippet in place of the Picasso code in the onPostExecute section - 

Glide.with(ArtistActivity.this).load(artist.getImageURL(ImageSize.MEGA)).diskCacheStrategy(DiskCacheStrategy.ALL).placeholder(R.drawable.art_default_xl).fitCenter().error(R.drawable.art_default_xl).into(backdrop);


Also, I'm exploring into the tag editor enhancement. I'll keep you posted

**Comment by marverenic** [comment]
I've moved the outstanding feature requests into separate issues since it's hard to keep track of lists like this one and has led to duplicate issues and outdated information here. See:
 - #66: Add a page specifically for recently added songs
 - #72: Retrieve missing album artwork from Last.fm
 - #75: Add the ability to edit a song's metadata
