### ISSUE TITLE
Error:(11, 40) error: cannot find symbol class JockeyComponentFactory

### ISSUE THREAD

**Issue by AKprisonER** [marverenic/Jockey#232]
This had happened of new build.All  gradle files has been updated,
But i cant find why this error is happening.**This had happened of new build.All  gradle files has been updated,
But i cant find why this error is happening**

**Comment by marverenic** [comment]
You may need to do a clean rebuild. Travis CI prevents any code from being committed to master before testing that it builds, so Jockey should always compile.

**Comment by AKprisonER** [comment]
i did that,but app  is generated for debug source...U could have move that jockeyapplication.java to the same folder where "main" is present.

**Comment by AKprisonER** [comment]
thanks i built it
