### ISSUE TITLE
[Bug] Fastscroller

### ISSUE THREAD

**Issue by Dirkstaal** [marverenic/Jockey#249]
![screenshot_2017-03-21-21-45-21](https://cloud.githubusercontent.com/assets/18539967/24167764/9e7b5744-0e80-11e7-82c6-b84c0ee34e2a.png)
Hi i have Samsung 5.1.1 Stock rom
happens if i use it and when it is released stays on the letter that was scrolled to last

**Comment by marverenic** [comment]
I was able to reproduce this in the latest beta version on Google Play (running on a Pixel XL with Android 7.1.2), but not the current version in `master`. I suspect that this is being caused by Proguard.
