### ISSUE TITLE
[Question] possible to remove retrolambda

### ISSUE THREAD

**Issue by Dirkstaal** [marverenic/Jockey#251]
Hi is it possible to remove retrolambda completely ?

**Comment by marverenic** [comment]
Jockey is using lambdas, so it is not possible to just remove Retrolambda. You would either need to switch to the Jack compiler (which is [deprecated](https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html)), or you would need to convert every lambda expression into an anonymous inner class, which would be tedious and would greatly reduce code clarity – especially with RxJava.
