### ISSUE TITLE
[Bug] Repeat

### ISSUE THREAD

**Issue by Dirkstaal** [marverenic/Jockey#269]
The repeating icons dont change .. and repeat one is not working playing one song even if i skip

**Comment by ThajKing** [comment]
The icons is changing correctly now but if repeat one song is on skipping to a next song the name changes but the previous song is repeated

**Comment by Dirkstaal** [comment]
The icons is changing
repeat(1) is not working correctly

if i enable repeat(1) 
skip or go to previous song
song title changes to the next song but the previous song is repeated always

so its repeating the track when repeat(1) was enabled
