### ISSUE TITLE
such a nice project but i cannot really use it

### ISSUE THREAD

**Issue by ThajKing** [marverenic/Jockey#273]
i am trying to get the audiosessionid but i cannot get it to work can anybody solve this ?

**Comment by marverenic** [comment]
@Dirkstaal had the same question, so you can refer to the discussion in #127, #137, #151, #252 and #261.

Here's the diff I provided him, with a fixed typo: [audioSessionId.zip](https://github.com/marverenic/Jockey/files/991423/audioSessionId.zip). Despite his comment in #261, I was able to verify that this code is working as intended in that it's passing ExoPlayer's AudioSessionID to the subscribers of `ServicePlayerController#getAudioSessionId()`.

Please consult the RxJava documentation if you have questions about how to use the return value of this method. You can also ask @Dirkstaal directly if he succeeded in getting this value.

**Comment by ThajKing** [comment]
ok thank you. 

But how do use it what should i call ?

example please 

equalizer = new Equalizer(Audiosessionid)

**Comment by ThajKing** [comment]
im not familiar with RxJava

**Comment by marverenic** [comment]
The diff includes an example in `NowPlayingFragment`. Put any code that relies on the audioSessionId in place of the `// TODO` comment. I would strongly suggest reading a couple of tutorials on RxJava to understand the basics before continuing with your modifications.

**Comment by Dirkstaal** [comment]
ok i got that part can i add the code anywhere else just removing
.compose() ?

or not

**Comment by ThajKing** [comment]
very good question @Dirkstaal 

Can i just do this in any of the classes ?
 .subscribe(audioSessionId -> {
                   // TODO do something with the audio session ID
                }, throwable -> {
                   Timber.e(throwable, "Failed to get audioSessionId");
                });

or is .compose(bindUntilEvent()); very important

**Comment by marverenic** [comment]
You _can_ remove it, but that would cause a memory leak – most likely of the entire Activity.

The `.compose(bindUntilEvent(FragmentEvent.DESTROY_VIEW))` call is adding a `Transformer` that automatically terminates the subscription when a specific lifecycle event happens (in this case when the fragment's view is destroyed). See the [RxLifecycle](https://github.com/trello/RxLifecycle) documentation for documentation on this, and for information about picking the right lifecycle transformer for your use.

An alternative is to remove the `.compose(...)` call, save the result of `.subscribe(...)`, and call `subscription.unsubscribe()` on it whenever your Activity is destroyed.

**Comment by ThajKing** [comment]
ok is there a way to test the audiosessionid before i actually implement something ?

**Comment by Dirkstaal** [comment]
i can finally confirm that Audiosessionid is working ☺

**Comment by Dirkstaal** [comment]
but it crashes after a minute then the Audiosessionid is 0 and then after a minute it crashes again then audiosessionid is correct ... and so on

**Comment by marverenic** [comment]
I don't know how I'm supposed to help you here. I have provided you with a working `getAudioSessionId()` method, but that is all that I can really give you. I have no idea what you mean when you say "it" is crashing, and quite frankly this question has been going on for far too long. You need to look at your stack trace, figure out what's causing the crash, and go from there. If it involves RxJava, then you need to read at least a couple of tutorials to understand the basics.

Take all debugging questions like this to an appropriate forum like StackOverflow. Again, any _general_ questions about Jockey's code are fine.
