### ISSUE TITLE
Fast scrollbar does not appear on most library pages

### ISSUE THREAD

**Issue by SzymonSporysz** [marverenic/Jockey#279]
This app makes browsing a large collection quite hard. I'd like to see a scrollbar. I think the native one with a letter popup would do.

**Comment by marverenic** [comment]
I believe the functionality you're describing is already in the app as of #220. It's still in the beta version of the app right now, so if you're using the version that's on the Play Store, it won't show up until the next update.

**Comment by SzymonSporysz** [comment]
I installed the beta version from Play and there's still no scrollbar on pages different than songs.

**Comment by marverenic** [comment]
Oh, that is definitely a bug. The scrollbars should appear on all the pages in the library.
