### ISSUE TITLE
Glitch?

### ISSUE THREAD

**Issue by balzathor** [marverenic/Jockey#28]
Found this glitch while playing music, downloaded the latest build from the play store. The app doesn't crash when I click on rewind button, but it sure is weird, I removed the music details, but the rewind button is glitchy, its the same in the notifcations too. Reboot didn't fix it, nor did clearing data. 

![Glitch](https://cloud.githubusercontent.com/assets/11243138/10930209/305be6a0-82e2-11e5-9fa1-c1fdc99846d0.png)

**Comment by marverenic** [comment]
There's actually a bug in the 5.0 platform that causes some Vector Drawables to render incorrectly like that. I think it has to do when you close a path and then relatively move to another area to begin a second path in the same data tag (which the sample material design icons that Google provides do from time to time). This had been working correctly until I recently switched to the gradle build tools to generate raster icons for older versions of Android (which supports the relative move operation, but doesn't support the reflection transformation I used to make it work previously), meaning that this only happens on devices running 5.0.

This should be resolved as of 8559d26.
