### ISSUE TITLE
Firebase support?

### ISSUE THREAD

**Issue by power7714** [marverenic/Jockey#309]
Can this be used to play a list of audio files from a Firebase node or can the feature be added?

**Comment by marverenic** [comment]
Jockey does not currently use Firebase or any other Google Play Services library. If you want to fork Jockey to make a streaming service that's backed by Firebase, then I don't see any reason you couldn't do this. 

You'd want to start off by creating a `FirebaseMusicStore` class that implements `MusicStore` and go from there. To use this throughout the app, look at `MediaStoreModule` in the `data.inject` package. If you're able to create `Song` models with resolvable URIs, then you shouldn't even have to modify the music playback service at all.
