### ISSUE TITLE
Missing word in beginning app disclaimer

### ISSUE THREAD

**Issue by supamunkey** [marverenic/Jockey#311]
The disclaimer dialog at the start of the Application contains a typo. The string resource containing this error is  **first_launch_detail**.

The exact sentence (added previous sentence for context): 
> All data collected is purely anonymous and helps greatly to improve Jockey. This information will kept confidential with Marverenic and is subject to the. . .

Corrected Sentence:

> This information will be kept confidential with Marverenic and is subject to the. . .

**Comment by marverenic** [comment]
Whoops – misclicked

**Comment by marverenic** [comment]
Thank you for pushing me on this. I have been putting this off for way too long...
