### ISSUE TITLE
I Cannot Change Package Name Successfully

### ISSUE THREAD

**Issue by Parlegrandpa** [marverenic/Jockey#315]
Hi

I'v been trying to change the package name of this project which results to a bunch of errors.
is it possible to change the package name from com.marverenic.music to com.xxx.music?
Kindly help with an explanation on how i can change package name successfully. Thank you

**Comment by Parlegrandpa** [comment]
is it possible to change the package name from com.marverenic.music to com.xxx.music?

**Comment by marverenic** [comment]
Check out #248.
