### ISSUE TITLE
Splash screen not charging 

### ISSUE THREAD

**Issue by AdebiyiPaul** [marverenic/Jockey#319]
Hi there,
I want to change the logo on the splash screen but it's not changing. I changed the image of I_splash, nothing happened. I changed the src in splash_background, nothing happened. 
Please where do I change it from? Thanks

**Comment by marverenic** [comment]
I think `res/drawable/splash_background.xml` is what you're looking for. It looks like the Jockey "J" is in `@drawable/ic_splash` and the Marverenic "M" is in `@drawable/ic_marverenic`.

**Comment by AdebiyiPaul** [comment]
I got that. All I needed to do was to restart my phone. Thanks
