### ISSUE TITLE
crash on app start

### ISSUE THREAD

**Issue by androrz** [marverenic/Jockey#32]
I get this error when trying to start jockey.

11-19 09:55:12.539: E/CrashlyticsCore(22473): .
11-19 09:55:12.539: E/CrashlyticsCore(22473): .     |  | 
11-19 09:55:12.539: E/CrashlyticsCore(22473): .     |  |
11-19 09:55:12.539: E/CrashlyticsCore(22473): .     |  |
11-19 09:55:12.539: E/CrashlyticsCore(22473): .   \ |  | /
11-19 09:55:12.539: E/CrashlyticsCore(22473): .    \    /
11-19 09:55:12.539: E/CrashlyticsCore(22473): .     \  /
11-19 09:55:12.539: E/CrashlyticsCore(22473): .      \/
11-19 09:55:12.539: E/CrashlyticsCore(22473): .
11-19 09:55:12.539: E/CrashlyticsCore(22473): This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
11-19 09:55:12.539: E/CrashlyticsCore(22473): install an Android build tool and ask a team member to invite you to this app's organization.
11-19 09:55:12.539: E/CrashlyticsCore(22473): .
11-19 09:55:12.539: E/CrashlyticsCore(22473): .      /\
11-19 09:55:12.539: E/CrashlyticsCore(22473): .     /  \
11-19 09:55:12.539: E/CrashlyticsCore(22473): .    /    \
11-19 09:55:12.539: E/CrashlyticsCore(22473): .   / |  | \
11-19 09:55:12.539: E/CrashlyticsCore(22473): .     |  |
11-19 09:55:12.539: E/CrashlyticsCore(22473): .     |  |
11-19 09:55:12.539: E/CrashlyticsCore(22473): .     |  |
11-19 09:55:12.539: E/CrashlyticsCore(22473): .
11-19 09:55:12.549: E/AndroidRuntime(22473): FATAL EXCEPTION: main
11-19 09:55:12.549: E/AndroidRuntime(22473): Process: com.marverenic.music.debug, PID: 22473
11-19 09:55:12.549: E/AndroidRuntime(22473): java.lang.RuntimeException: Unable to create application com.marverenic.music.JockeyApplication: io.fabric.sdk.android.services.concurrency.UnmetDependencyException: com.crashlytics.android.core.CrashlyticsMissingDependencyException: 
11-19 09:55:12.549: E/AndroidRuntime(22473): This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
11-19 09:55:12.549: E/AndroidRuntime(22473): install an Android build tool and ask a team member to invite you to this app's organization.
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4613)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at android.app.ActivityThread.access$1500(ActivityThread.java:159)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1389)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at android.os.Handler.dispatchMessage(Handler.java:110)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at android.os.Looper.loop(Looper.java:193)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at android.app.ActivityThread.main(ActivityThread.java:5367)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at java.lang.reflect.Method.invokeNative(Native Method)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at java.lang.reflect.Method.invoke(Method.java:515)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:663)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at dalvik.system.NativeStart.main(Native Method)
11-19 09:55:12.549: E/AndroidRuntime(22473): Caused by: io.fabric.sdk.android.services.concurrency.UnmetDependencyException: com.crashlytics.android.core.CrashlyticsMissingDependencyException: 
11-19 09:55:12.549: E/AndroidRuntime(22473): This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
11-19 09:55:12.549: E/AndroidRuntime(22473): install an Android build tool and ask a team member to invite you to this app's organization.
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at com.crashlytics.android.core.CrashlyticsCore.onPreExecute(CrashlyticsCore.java:277)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at com.crashlytics.android.core.CrashlyticsCore.onPreExecute(CrashlyticsCore.java:231)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at io.fabric.sdk.android.InitializationTask.onPreExecute(InitializationTask.java:44)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at io.fabric.sdk.android.services.concurrency.AsyncTask.executeOnExecutor(AsyncTask.java:611)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at io.fabric.sdk.android.services.concurrency.PriorityAsyncTask.executeOnExecutor(PriorityAsyncTask.java:43)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at io.fabric.sdk.android.Kit.initialize(Kit.java:66)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at io.fabric.sdk.android.Fabric.initializeKits(Fabric.java:439)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at io.fabric.sdk.android.Fabric.init(Fabric.java:383)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at io.fabric.sdk.android.Fabric.setFabric(Fabric.java:340)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at io.fabric.sdk.android.Fabric.with(Fabric.java:311)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at com.marverenic.music.JockeyApplication.onCreate(JockeyApplication.java:12)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4610)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	... 10 more
11-19 09:55:12.549: E/AndroidRuntime(22473): Caused by: com.crashlytics.android.core.CrashlyticsMissingDependencyException: 
11-19 09:55:12.549: E/AndroidRuntime(22473): This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
11-19 09:55:12.549: E/AndroidRuntime(22473): install an Android build tool and ask a team member to invite you to this app's organization.
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at com.crashlytics.android.core.BuildIdValidator.validate(BuildIdValidator.java:59)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at com.crashlytics.android.core.CrashlyticsCore.setAndValidateKitProperties(CrashlyticsCore.java:308)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	at com.crashlytics.android.core.CrashlyticsCore.onPreExecute(CrashlyticsCore.java:253)
11-19 09:55:12.549: E/AndroidRuntime(22473): 	... 22 more

**Comment by marverenic** [comment]
If you're building Jockey from source, then you'll get this error because you haven't specified a Crashlytics API key (I don't post my API key to the repo since experience shows that I'll get crash reports from every fork of Jockey otherwise. In fact there's a fork on the Google Play store right now that's using my API key and I'm getting all of its crash reports)

You can safely ignore this error, but if you want to make it go away on your own builds then you have a couple options. You can either remove the Crashlytics dependency from app/build.gradle and delete all references to it, or you can specify your own Crashlytics API key if you have one in either AndroidManifest.xml or app/fabric.properties as mentioned in the project's README.md

**Comment by androrz** [comment]
@marverenic Thnaks
