### ISSUE TITLE
Couldn't find IPlayerService in the code...

### ISSUE THREAD

**Issue by salvator91** [marverenic/Jockey#33]
What is IPlayerService? Couldn't locate it in the source code

**Comment by marverenic** [comment]
IPlayerService is an [AIDL](http://developer.android.com/guide/components/aidl.html) interface used to send commands to the remote player service. You can find the AIDL definition in [Jockey/app/src/main/aidl/com/marverenic/music/IPlayerService.aidl](https://github.com/marverenic/Jockey/blob/master/app/src/main/aidl/com/marverenic/music/IPlayerService.aidl).

IPlayerService.Stub is the main class used to communicate across processes which is generated by the AIDL build tools when compiling the project. If you're interested in its source code (which is remarkably ugly), you'll have to navigate to the source in one of the generated directories.
