### ISSUE TITLE
Can't find SeekBar implementation in your code

### ISSUE THREAD

**Issue by salvator91** [marverenic/Jockey#35]
Have you removed the seekbar code from your NowPlayingActivity?

**Comment by marverenic** [comment]
In commit b8e6cf0b2bac3ed5fefb6451fdef53cdb67e818e, the Seekbar code was moved from NowPlayingActivity to [PlayerControllerFragment](https://github.com/marverenic/Jockey/blob/b8e6cf0b2bac3ed5fefb6451fdef53cdb67e818e/app/src/main/java/com/marverenic/music/fragments/PlayerControllerFragment.java). Although it's not the most conventional use of a Fragment, it helps keep a lot of logic out of the Activity and makes the now playing layout a bit easier to manage.
