### ISSUE TITLE
remove drop-down menu from repeat item

### ISSUE THREAD

**Issue by gharibeh** [marverenic/Jockey#353]
if you remove the drop-down menu from repeat item in the head of the playlist, it will be so user-friendly.
you can remove the drop-down menu and add changeable button icon instead.
for example first click on the icon for repeat one - second click for repeat all - third click for repeat none - long press for multi-repeat.

**Comment by marverenic** [comment]
I think the menu is fine as it is. Most users would be familiar with cycling through the repeat modes, but the long-press to access multi-repeat buries it in a non-intuitive location which conflicts with the default behavior of showing the tooltip.

The alternative would be to make the icon cycle between the standard modes and move the multi-repeat option into the regular menu, but then this splits apart similar behavior into two separate locations. The current menu approach at worst adds one additional button press to switch modes, which I don't feel warrants redoing this menu.
