### ISSUE TITLE
Cannot play high sample rate files (e.g 192 kHz)

### ISSUE THREAD

**Issue by critbase** [marverenic/Jockey#354]
My music library is mostly FLAC files, and most of them, are 44.1 kHz. For the few songs I have at 192 kHz, Jockey stops playback and throws an error "[Song] can't be played." Then it is unable to play any other song that is queued.

**Comment by marverenic** [comment]
Unfortunately, it looks like this is a bug in ExoPlayer, not Jockey: https://github.com/google/ExoPlayer/issues/3769. I'll keep an eye on it and update the version of ExoPlayer Jockey uses when a fix is released, but it sounds like it may not be for a while 😢. 

In the meantime, you may have to reencode high bitrate music to play it with Jockey. Sorry about that.
