### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by Hamzeto938** [marverenic/Jockey#357]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate either here or via email, so I don't have to create issues. Thank you.

**Comment by marverenic** [comment]
Jockey already has a decent amount of copy both on GitHub and Google Play, so I'm not sure exactly what you have in mind here. That being said, anyone can open a PR without permission, so feel free to revise or expand on whatever you want and we can discuss the changes when you're ready to merge.

If you have any specific questions about this, feel free to post them in this issue or use the email address on my profile.

**Comment by Hamzeto938** [comment]
i am thinking about creating a Frequently asked question and an about us especially to address quick issues users get with the app

**Comment by marverenic** [comment]
Having an FAQ could be nice, but I think an "About Us" document is unnecessary (and a bit inaccurate as there's only one dev). I'm gonna close this issue, but feel free to shoot me an email if you have any follow-up questions here.
