### ISSUE TITLE
.wav files are not supported

### ISSUE THREAD

**Issue by salvator91** [marverenic/Jockey#36]
Can't play wav files from file manager

**Comment by marverenic** [comment]
Which version of Jockey are you currently using?

I tested .wav playback from [Cabinet](https://play.google.com/store/apps/details?id=com.afollestad.cabinet) on version 1.1.3 in an emulator, and it was able to play a .wav file I added to the SD Card after the MediaStore found it.

On 1.2 beta 2, however, I couldn't get Jockey to play any music from a file manager, meaning that I probably broke something important in 7586dd4b30cfe5ca29e5bfacd562ef14ed285c22 that I'll be looking into soon.

If you could provide more information about what phone you're using (i.e. model, android version, file location, etc.), that would help a lot. If you've recently added the song or it's not appearing in the main library page, you can also try to rescan the MediaStore either with an app from the Play Store or the command `adb shell am broadcast android.intent.action.MEDIA_MOUNTED`.

**Comment by marverenic** [comment]
I'm going to close this due to inactivity, but if it's still a problem, feel free to create a new issue or reply to this one to have it reopened.
