### ISSUE TITLE
I'd like to contirubute to Jockey Music Player

### ISSUE THREAD

**Issue by HarryHeights** [marverenic/Jockey#370]
Hello, I'm Harry. I'm a creative writer and a content creator. I contribute to projects by creating copywriting documents for them. Copywriting serve as a written way to advertise a product or a service or a software as is in this case.
It could be an About Us, FAQs, Contact Us, Privacy Policy document. However I noticed in your readme file that you have already covered part of the constituents for a privacy policy so I'm opting to create an About Us document and a compilation of FAQs. The About Us document is a general summary of your project and you as they and it'll be composed in a way to generate interest to new users of the app. FAQs would serve as a self service for basic and even complex questions end users may want to ask. 

I hope to get a reply from you.

**Comment by marverenic** [comment]
You don't need permission to contribute to Jockey 🙂

Check out #357. Someone asked a similar question, but I haven't heard back from them since. An FAQ would be nice, but an "About us" page seems a bit unnecessary (and technically incorrect since Jockey is a side project maintained by a single dev).

**Comment by HarryHeights** [comment]
Okay. I just had to go over it with you first. I really don't like
intruding. Not all the project owners I've contacted seemed okay with the
idea that's why I considered it necessary to always make a proposal. Thanks
for your response I'll submit a compilation of the FAQs so we can go over
it together and see which questions are necessary. Thanks for your reply.
Btw About Us necessarily don't mean you've got to have a team. It could
simply be termed "About", and it's about the project itself not necessarily
the owner. I'm glad you responded. I'll get back to you soon

**Comment by HarryHeights** [comment]
Hello. I was late to deliver on the FAQs document. Had some other jobs I needed to work on. I've created a pull request for he document. 
There maybe some things in it you might want to modify, add or remove so please proof read the document. 

Thanks and have a nice day.
