### ISSUE TITLE
Playlists gone

### ISSUE THREAD

**Issue by LeHman93** [marverenic/Jockey#389]
**Describe the bug**
After updating to the latest version of Ymusic i had to re login and couldn't find my playlists, talking about the custom ones made in the app not the ones from youtube, and it seems that after creating a new local playlist the songs didn't save to it, initially they did but after a bit i couldn't add the songs to it and when i looked at it in the library it was empty

**Expected behavior**
Updated to the latest version

**Actual behavior**
Keep my playlists between updates

**Device information:**
Samsung galaxy J7

**Comment by marverenic** [comment]
Unfortunately, I'm not able to respond to issues in apps derived from Jockey (like YMusic). There's a chance that the issue is only in YMusic, so I can't do anything here unless you're able to reproduce the issue in Jockey.

Have you tried reaching out to the developer of YMusic?

**Comment by LeHman93** [comment]
Well thanks for the response, i thought looking at source was the thing to but ill try that
