### ISSUE TITLE
Using JSON to play files from internet web server

### ISSUE THREAD

**Issue by ibyteapps** [marverenic/Jockey#408]
**Is your feature request related to a problem? Please describe.**
I'm unable to understand how the json files included in the project work. I've spent a few hours studying the project today. 

**Describe the solution you'd like**
I'd love to use json files to play mp3 files from my own internet web server instead of scouring the local media. 

Any help would be truly appreciated.

**Comment by marverenic** [comment]
Are you referring to the files in the [demo-library](https://github.com/marverenic/Jockey/tree/c40f3478b7742206dd829a5268cb1f13ea53f12e/demo-library) folder? Those are only intended to be used for creating promotional material like screenshots for the Google Play Store, as the readme describes.

Currently, it isn't possible to have Jockey display music that is not already on your device. You _can_ use Jockey to open music files from another app (and Jockey _will_ stream them if necessary), but Jockey's library UI will only display local content. It's possible to connect Jockey to cloud-based services if you want to get your hands dirty in the code, but there are quite a few features that are taking priority at the moment.

It sounds like you're managing your own server -- have you considered using something like [Plex](https://www.plex.tv/your-media/) instead?

**Comment by ibyteapps** [comment]
Thanks for your prompt response. I've figured out a way to adapt the project to my own needs. I'll work on some code and figure out a way to import data from json. What other features are taking priority at your end?

**Comment by marverenic** [comment]
Good to hear you were able to find a solution!

If you want all of the juicy details on Jockey's roadmap, you can check out the [Pivotal Tracker project](https://www.pivotaltracker.com/n/projects/1594253).

From a high level, there's a lot of refactoring work I want to do in the short term to modernize a lot of the architecture. Next comes some finishing touches for Android Auto for a 3.1 release. Afterwards, there are a number of improvements I want to make that are living in the icebox. The top priority there is metadata editing, but I don't have a good feel for priority afterwards (The order in the icebox isn't really accurate as far as priority goes).
