### ISSUE TITLE
Few issues and suggestions

### ISSUE THREAD

**Issue by salvator91** [marverenic/Jockey#46]
1. The getArtwork() method in PlayerController sometimes produces OutOfMemory Error in my device(Api 19). I am guessing you need to add some Bitmap Factory tweaks to keep the image size within memory budget.
http://stackoverflow.com/questions/477572/strange-out-of-memory-issue-while-loading-an-image-to-a-bitmap-object

2. Please add a clear queue option in the PlayerService stub. I tried to do so myself but it led to disastrous result. So gave up.

3. The album page fails to retrieve a lot of artwork while scrolling in case there are many albums.

**Comment by salvator91** [comment]
Actually the problem is with fetchFullArt() method in Utils.

**Comment by marverenic** [comment]
Your second point about adding a button to clear the queue should be resolved in 6a9b102. I've made a separate issue (#46) for the `OutOfMemoryError`.
