### ISSUE TITLE
Would love to see this buildable from AOSP

### ISSUE THREAD

**Issue by shkschneider** [marverenic/Jockey#53]
That would mean an Android.mk.

(Will investigate a bit.)

**Comment by shkschneider** [comment]
Too much dependencies...

I went as far as:
`LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_RESOURCE_DIR := $(LOCAL_PATH)/res
LOCAL_RESOURCE_DIR += frameworks/support/v7/appcompat/res
LOCAL_RESOURCE_DIR += frameworks/support/design/res
LOCAL_RESOURCE_DIR += frameworks/support/v7/preference/res
LOCAL_SRC_FILES := $(call all-java-files-under, src)
LOCAL_STATIC_JAVA_LIBRARIES += android-support-v7-appcompat
LOCAL_STATIC_JAVA_LIBRARIES += android-support-v7-preference
LOCAL_AAPT_FLAGS := --auto-add-overlay
LOCAL_AAPT_FLAGS += --version-name "$(version_name_package)"
LOCAL_AAPT_FLAGS += --version-code $(version_code_package)
LOCAL_AAPT_FLAGS += --extra-packages android.support.v7.appcompat
LOCAL_AAPT_FLAGS += --extra-packages android.support.support
LOCAL_AAPT_FLAGS += --extra-packages android.support.v7.preference
LOCAL_PACKAGE_NAME := Music
LOCAL_SDK_VERSION := current
LOCAL_PROGUARD_FLAG_FILES := proguard.flags
include $(BUILD_PACKAGE)`

**Comment by marverenic** [comment]
Sorry I haven't replied to this until now. I'm not sure I understand the benefit of this (it also looks like `Android.mk` files usually involve projects using the NDK).

Like most other apps, Jockey can be built from gradle, so adding support for another build system seems like a lot of work for no real benefit. Feel free to let me know if there's something I'm missing, though.
