### ISSUE TITLE
Last.fm integration

### ISSUE THREAD

**Issue by marverenic** [marverenic/Jockey#6]
More thorough Last.fm integration including an artist bio page accessed by clicking on the artist page header and suggested artists & albums.

Other features like lyrics, links to purchase more music, and fetching missing music tags are under consideration, but probably won't make it in before the first beta release.

Scrobbling and other account-related actions probably won't make their way to Jockey (at least for the time being) simply because it's probably not a good idea to trust a CS freshman to store passwords.

**Comment by maysleazy** [comment]
Can you just add a link "Read more on Last.Fm" to the artist information, because I wouldn't love reading incomplete information and I bet no one does. Shouldn't be much of a problem to add a link though.

**Comment by f1u77y** [comment]
> Scrobbling and other account-related actions probably won't make their way to Jockey (at least for the time being) simply because it's probably not a good idea to trust a CS freshman to store passwords.

What if you send the info about now playing songs to some aggregator scrobbler app like [tgwizard/sls](https://github.com/tgwizard/sls)? Users still need to store their info in that app but that's their choice, isn't it?

**Comment by marverenic** [comment]
Luckily I'm not a freshman anymore 😉. Last.fm's authentication API doesn't require applications to store user passwords at all, so it seems pretty straightforward to keep login information secure. I'd also prefer to avoid a dependency on another application simply because it adds so points of failure and isn't strictly required here.

It doesn't look like there's a GitHub issue for Scrobbling to Last.fm, so please feel free to make one.

**Comment by f1u77y** [comment]
> I'd also prefer to avoid a dependency on another application simply because it adds so points of failure and isn't strictly required here.

Okay, on the one hand it is but on the other hand:

- It's more simple to do this. You should only [submit the current state when it changes](https://github.com/tgwizard/sls/wiki/Developer's-API).
- It's the most common way of doing this. I've seen dozens of apps which use this way (even the default Android 4.x music player was doing this) but only one (or maybe two...) apps which submits by itself.
- Its features (like some compatible services or adjusting scrobbling logic) are developed independently and are applied to all the music apps on the device (e.g. your one and some streaming service).
