### ISSUE TITLE
Well, here comes another bug..

### ISSUE THREAD

**Issue by captainfenix** [marverenic/Jockey#9]
Song name in the app and notification does not update for non album artwork songs.

**Comment by marverenic** [comment]
I think I've found a simple solution to this that fixes this issue when beginning playback of a song with no art on the now playing page. I haven't noticed it anywhere else in the future release, so it might have already been resolved with a lot of the UI changes I've made.

**Comment by maysleazy** [comment]
Now the actionbar color stays blue for any primary color...

**Comment by marverenic** [comment]
I found the problem. On API < 21 the actionbar used to be colored separately after the activity was themed. Since m20, it's part of the theme declared in styles.xml, but a method wasn't updated to reflect this.

**Comment by captainfenix** [comment]
Did you fix this yet?

**Comment by marverenic** [comment]
I think it's been fixed for a while, actually. I just tested it and it appears to work, but let me know if it's still a problem.

**Comment by captainfenix** [comment]
Must have been fixed, works now.
