### ISSUE TITLE
Add the ability to browse music libraries by folder

### ISSUE THREAD

**Issue by iampawan** [marverenic/Jockey#97]

**Comment by marverenic** [comment]
Just to make sure I understand what you're asking, you're asking for the ability to browse your music library by folder, right? Something like what Phonograph and others do?
![screenshot_2016-07-24-13-18-15](https://cloud.githubusercontent.com/assets/10948413/17085227/4be5a35a-51a1-11e6-88ef-3df33244b809.png)

**Comment by iampawan** [comment]
Yes this what i m asking for and sleep timer to stop music after a specific time @marverenic

**Comment by marverenic** [comment]
Okay. I'm going to change the title to make that more clear then. Also, sleep timers have a separate issue thread (#73), so I'm going to remove that from this issue.

**Comment by iampawan** [comment]
Yeah sure .. Thanks , you are awesome.

**Comment by Dirkstaal** [comment]
Ive seen 2 open source music players with folder tab...
Vanilla music player and Jams Music player maybe it could help a bit :)

**Comment by Khang-NT** [comment]
Instead of browsing music by folder like the UI design above, Jockey can simply add a way to create Smart playlist and filter songs in specific directory (maybe plus subdirectory).
